### ISSUE TITLE
Cannot get certificate - probe test fails

### ISSUE THREAD

**Issue by AnthonyBe** [ridercz/AutoACME#22]
I've just gone through the setup and the script is failing on the probe test on my system:

```
C:\Scripts\CertStore\AutoACME>autoacme addhost anthonyb.no-ip.biz
Altairis AutoACME Manager version 1.5.4.0
Copyright (c) Michal A. Valasek - Altairis, 2017
www.autoacme.net | www.rider.cz | www.altairis.cz

Reading configuration from 'C:\Scripts\CertStore\AutoACME\autoacme.json'...OK
Checking host...OK
Requesting cerificate for anthonyb.no-ip.biz:
  Accepting TOS at https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf...OK
  Testing authorization:
    Writing challenge to C:\InetPub\wwwroot\AutoAcme\probe_b0775ef5-9764-4a0c-a130-4eb8c1c2381e...OK
    Testing HTTP challenge:
      Preparing request to http://anthonyb.no-ip.biz/.well-known/acme-challenge/probe_b0775ef5-9764-4a0c-a130-4eb8c1c2381e...OK
      Getting response...Failed!
      The remote server returned an error: (404) Not Found.
    Testing HTTPS challenge:
      Preparing request to https://anthonyb.no-ip.biz/.well-known/acme-challenge/probe_b0775ef5-9764-4a0c-a130-4eb8c1c2381e...OK
      Getting response...Failed!
      Unable to connect to the remote server
    Deleting challenge from C:\InetPub\wwwroot\AutoAcme\probe_b0775ef5-9764-4a0c-a130-4eb8c1c2381e...OK
  Request failed: One or more errors occurred.
  Failed!
  Unable to get certificate for new host.
```

I've dropped a configcheck text file in the C:\inetpub\wwwroot\AutoACME folder for testing.
If I browse directly to https://anthonyb.no-ip.biz/AutoACME/configcheck then the text file contents are shown, i.e. test works.
If I browse to https://anthonyb.no-ip.biz/.well-known/acme-challenge/configcheck then I get HTTP Error 404
I've also tried with and without the web.config file in the AutoACME folder as I've seen IIS sometimes throw HTTP 500s but it made no difference.

My system is Windows Server 2012 R2 / IIS 8.5 with all current public Windows Update patches installed.
The AutoACME.json file produced by the script config  looks fine based on comparison to the docs.

Any thoughts on what I can check next to work out why this is failing on, what looks to be, the URL re-write?

**Comment by ridercz** [comment]
You seem to have some strange configuration, because the `https://anthonyb.no-ip.biz/AutoACME/configcheck` address should not work. I infer that you have the `anthonyb.no-ip.biz` bound to the _Default Web Site_. 

This is kind of unusual configuration. Usually the _Default Web Site_ is left intact as a fallback site and the production sites are created as new virtual web servers. AutoACME is intended for this kind of scenario.

If you have only single site on your server, then you can omit the URL rewriting and set the `C:\InetPub\wwwroot\.well-known\acme-challenge` folder as `ChallengeFolder` in the configuration file. AutoACME is very complicated solution for a single web site, is intended for servers with tens, hundereds or thousands of sites. But it should work.

**Comment by AnthonyBe** [comment]
Ah. You are spot on. And yes, I forgot I had bound anthonyb.no-ip.biz to the website while trying to use another SSL Certificate automation solution.

As soon as I removed that hostname from the binding it all worked perfectly and I have HTTPS up and running.

Thank you so much!
