### ISSUE TITLE
Getting 404 and AutoACME HTTP Error 403.14 - Forbidden

### ISSUE THREAD

**Issue by Swoox** [ridercz/AutoACME#25]
I follow the guide ((https://github.com/ridercz/AutoACME/wiki/Getting-started-with-AutoAcme#HTTPS-setup) of getting started I'm to the point to excute `autoacme addhost`.
If I browse to : 
http://localhost/autoACME/ 
I get a HTTP Error 403.14 - Forbidden.

I tried to put `<directoryBrowse enabled="true" />` in the web.config and it succesfully open.

Also getting 404 error when excuting `autoacme addhost`. 
Am I doing something wrong?

**Comment by ridercz** [comment]
> If I browse to: http://localhost/autoACME/ I get a HTTP Error 403.14 - Forbidden.

That's perfectly normal and it says so because there is no default document and directory browsing is disabled. If you want to test everything is working, create a file there (ie. new.txt) and then ask for it  (http://localhost/autoACME/new.txt).

> Also getting 404 error when excuting autoacme addhost.
> Am I doing something wrong?

Probably, but I can't tell you more without the full log. My bet is that you don't have URL routing setup correctly.
