### ISSUE TITLE
Requesting certificate...Renewal failed: One or more errors occurred

### ISSUE THREAD

**Issue by kine** [ridercz/AutoACME#3]
Hi,
the renew is failing for me for some time and I cannot find why. Another thing is, that if it fail, the host is removed from the config, thus I need to re-add it again.

The end of the output is this:
```
   Completing challenge...OK
    Waiting for authorization...OK
    Deleting challenge from C:\InetPub\wwwroot\AutoAcme\xxxxxxxxxxxxxx ...OK
  Processing certificate:
    Requesting certificate...Renewal failed: One or more errors occurred.
  Loading hosts expired at least 30 days ago...OK, 1 hosts to purge:
    Host XXXX.XXX.XXX expired 32 days ago (22. listopadu 2017)
      Deleting from database...OK
      Deleting files:
        Deleting file C:\CertStore\PFX\xxxx.xxx.xxx.pfx...OK
  Saving configuration to 'C:\AutoACME\autoacme.json'...OK
```

How can I enable some verbose mode to see more info?

**Comment by kine** [comment]
Ok, today working. And I have found that I can use /verbose to get more details. Thanks. Closing.

**Comment by ridercz** [comment]
I'll just add that the removal of expired certificate is intentional. AutoACME by default deletes hosts whose certs expired more than 30 days ago, as self-cleaning mechanism. It it was unable to get fresh cert for 60 days (30 days before expiration and 30 after) and user was not reacting to numerous emails sent by Let's encrypt, there is no hope left.

You may set the time interval using [PurgeDaysAfterExpiration](https://github.com/ridercz/AutoACME/wiki/Configuration-file-reference#purgedaysafterexpiration) variable in configuration file.

You may also disable this functionality completely by never running the `purge` or `maintenance` commands automatically and running only `renew`. The not working hosts would then pile up until manually cleaned.
