### ISSUE TITLE
IIS rewrite url is not work

### ISSUE THREAD

**Issue by mk148a** [ridercz/AutoACME#48]
Hi there,
I am following the instructions:https://github.com/ridercz/AutoACME/wiki/Getting-started-with-AutoAcme
the iis rewrite url rule is not work perfectly, but autoacme is not create file, its reason for 404 i think.

![1](https://user-images.githubusercontent.com/7630189/86521118-4d80b680-be55-11ea-86e3-e9aa1da23c39.JPG)

**Comment by ridercz** [comment]
It does not work, because you setup it wrong.

The challenge is generated into `C:\Inetpub\wwwroot\AutoAcme` and you're rewriting to `C:\Inetpub\wwwroot\something\AutoAcme`, the folder where AutoACME is installed.

This is wrong on several levels:

1. You want the rewrite to the folder where you generate the challenge.
2. You don't want the AutoACME folder to be publicly accessible via web.

**Comment by mk148a** [comment]
ohh thank you!
